sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: mBOo15dIOTengsCSZKPwbP3zxWkOmLTVbcbhd6DOQBfwmgTVWTHJKAEtouFStSphZDsh7q+yMuVkby1/JHgAWGoj5tNZri67FjBEBnqGfZpZfEOwfET9z2LXL3THVCKHmx+yfLcqGnKTLDkPVMXaE5Jt3VGb5p71nulWQOFlNt1ulVdEr01NVmwX9iRCQNZCak5IyKEOKEua0lK9b70JvkxxARTDMcA1UQZLrRSM8HwwX2JQVGRNS5k0fGSAy+5oZgdvNuG0Jvd+ntZ5xVoeTfuEk4JEEuJ66T3mac8hXl4qPqufvIMUYIeJrjrKXNN7DcLCCPaPS2rKheinXAW9iIFL4iSdpRW3KA7jOx0KF3lfOJxJMwbnzzVWs+ILGibZn1VD6Ck/FF4cMc9hgiyKJOhVaUpI+r1+gwhTS6ftu9gRX2Mu1x2VZxGM2UOBJzPLVCxWIYyJl6hwSdl4uoQwDt0sVDIY4fWomICz3tbbcOAkF7EB/26wm1FE47sUYKftyZTox7jdPrxjWPvNz1qXt8ujOfmFfcnhRKUzR7RKmhMrOpgmUJRlAozItjkhPPB+9ow+D0/vLFux1adY4WQHBqbSpqWyM6Fh3/LZTfSklj9HZao8sax3bwUn7isbq/9Cyo+JnES0QM7kKqktvkcNH7Uf9RJ8nefD1SvN8XQ90D8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Evergreens_857
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy